### ISSUE TITLE
After recent patch, If the length of protein langer than 30, run_model() will fail.

### ISSUE THREAD

**Issue by haohaohtc2010** [HAMdetector/Escape.jl#4]
Hi Daniel,
recently when I tried to run_model(HLAData) , there will be an issue during the stan iteration as follow. After testing, I found that if the protein length <=30, it goes well, otherwise issue.

......(init log)

Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception: Exception: bernoulli_logit_glm_lpmf: Weight vector[1] is -nan, but must be finite! (in '../Escape.jl/models/model_4.stan', line 43, column 12 to line 47, column 26) (in '../Escape.jl/models/model_4.stan', line 169, column 8 to column 71)
Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception: Exception: bernoulli_logit_glm_lpmf: Weight vector[1] is -nan, but must be finite! (in '../Escape.jl/models/model_4.stan', line 43, column 12 to line 47, column 26) (in '../Escape.jl/models/model_4.stan', line 169, column 8 to column 71)

.......(same as above)

Initialization between (-2, 2) failed after 100 attempts. 
 Try specifying initial values, reducing ranges of constrained values, or reparameterizing the model.
Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception: Exception: bernoulli_logit_glm_lpmf: Weight vector[1] is -nan, but must be finite! (in '../Escape.jl/models/model_4.stan', line 43, column 12 to line 47, column 26) (in '../Escape.jl/models/model_4.stan', line 169, column 8 to column 71)
Initialization failed.
failed process: Process(`env STAN_NUM_THREADS=-1 /tmp/jl_N3Is8w sample num_samples=1000 adapt delta=0.85 algorithm=hmc engine=nuts max_depth=10 num_warmup=300 data file=/tmp/jl_s0Uoh5 random seed=7907146 output refresh=1 file=/tmp/jl_PTOJGx id=1`, ProcessExited(1)) [1]

Stacktrace:
  [1] (::Base.var"#892#894")(x::Task)
    @ Base ./asyncmap.jl:177
  [2] foreach(f::Base.var"#892#894", itr::Vector{Any})
    @ Base ./abstractarray.jl:2694
  [3] maptwice(wrapped_f::Function, chnl::Channel{Any}, worker_tasks::Vector{Any}, c::UnitRange{Int64})
    @ Base ./asyncmap.jl:177
  [4] wrap_n_exec_twice
    @ ./asyncmap.jl:153 [inlined]
  [5] async_usemap(f::StanInterface.var"#launch_stan#12"{Int64, Int64, Int64, Int64, Int64, String, StanInterface.StanIO{String, Vector{String}}}, c::UnitRange{Int64}; ntasks::Int64, batch_size::Nothing)
    @ Base ./asyncmap.jl:103
  [6] #asyncmap#876
    @ ./asyncmap.jl:81 [inlined]
  [7] stan(model::String, data::Dict{String, Any}; iter::Int64, chains::Int64, warmup::Int64, ntasks::Int64, nthreads::Int64, refresh::Int64, seed::Int64, wp::Distributed.WorkerPool, run_diagnostics::Bool, stan_args::String, save_binary::String, save_data::String, save_result::String, save_diagnostics::String)
    @ StanInterface ~/projects/StanInterface/src/StanInterface.jl:169
  [8] (::Escape.var"#125#126"{4, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, Dict{String, Any}})(exe::String)
    @ Escape ~/.julia/packages/Escape/FDZ5W/src/hla_model.jl:66
  [9] (::JLLWrappers.var"#2#3"{Escape.var"#125#126"{4, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, Dict{String, Any}}, String})()
    @ JLLWrappers ~/.julia/packages/JLLWrappers/QpMQW/src/runtime.jl:49
 [10] withenv(::JLLWrappers.var"#2#3"{Escape.var"#125#126"{4, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, Dict{String, Any}}, String}, ::Pair{String, String}, ::Vararg{Pair{String, String}})
    @ Base ./env.jl:172
 [11] withenv_executable_wrapper(f::Function, executable_path::String, PATH::String, LIBPATH::String, adjust_PATH::Bool, adjust_LIBPATH::Bool)
    @ JLLWrappers ~/.julia/packages/JLLWrappers/QpMQW/src/runtime.jl:48
 [12] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./essentials.jl:716
 [13] invokelatest(::Any, ::Any, ::Vararg{Any})
    @ Base ./essentials.jl:714
 [14] model_1(f::Function; adjust_PATH::Bool, adjust_LIBPATH::Bool)
    @ HAMdetector_model_binaries_jll ~/.julia/packages/JLLWrappers/QpMQW/src/products/executable_generators.jl:21
 [15] model_1(f::Function)
    @ HAMdetector_model_binaries_jll ~/.julia/packages/JLLWrappers/QpMQW/src/products/executable_generators.jl:21
 [16] run(model::HLAModel{4}, data::HLAData; keep_all_parameters::Bool, stan_kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Escape ~/.julia/packages/Escape/FDZ5W/src/hla_model.jl:63
 [17] run_model(data::HLAData; keep_all_parameters::Bool, save_file::String, stan_kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Escape ~/.julia/packages/Escape/FDZ5W/src/hla_model.jl:15
 [18] run_model(data::HLAData)
    @ Escape ~/.julia/packages/Escape/FDZ5W/src/hla_model.jl:10
 [19] top-level scope
    @ In[70]:2

**Comment by haohaohtc2010** [comment]
This issue happens only for certain sequence, not general.

**Comment by daniel-habermann** [comment]
The issue you are seeing is Stan failing to initialize, probably because some of the inputs are so far off that we get numerical under/overflow in some of the parameters. This most likely means that some of the inputs are not correct, probably the phylogenetic tree or epitope predictions. I suspect this is not a software issue with HAMdetector, but rather a problem with input data.

Please answer the following questions so we can pinpoint the issue:

1. Did the model run fine using the same inputs with an earlier version of HAMdetector? (I suspect this is not the case)

2. Is it possible for you to share the input data with me? That would make debugging a bit easier. But please be mindful of any privacy concerns as HLA data is sensitive personal information.

3. Can you identify if any single sequence is causing the issue? For that, you can use a bifurcation strategy: Remove one-half of the sequences and try to see if the issue persists. Then try the same with the other half. Are both halves causing Stan to error? If not, repeat until you have located the sequence.

4. Try running a model without phylogeny. For this, use this code:

```julia
using Escape

data = HLAData(
    alignment_file = "/home/user/Desktop/alignment.fasta",
    tree_file = "/home/user/Desktop/phylogeny.tree"
)

result = run_model(HLAModel{3}(), data)
```

Does this model run without issue? If not, try going down to model 2 and 1. This may help us tell which part of the input might be the issue.

You can also try to see if you can spot any issues in the input data manually. For this, run `d = Escape.compute_stan_input(data)`, in particular, check the elements of the "X", "y", "phy" and "Z" keys of the returned dictionary. Things to look out for: Are there any entries that are infinite? Is `d["X"]`
 a matrix of 1s and 0s? Do we have any entries in `d["phy"]` that are 0 or 1? Is `d["Z"]` a matrix of 1s and 0s?

**Comment by haohaohtc2010** [comment]
Hi Daniel, thank you for the answer.
As for your questions,
1. I didn't try it with the data before, so I have no idea if it work before, but yea I guess this is not the case as well.
2. I can share you the data, they are segments from a long protein, so there shouldn't be privacy problem. (see bottom)
3. I'm not fimilar with the phylogeny tree, I don't know how to cut the tree into half since the number of sequences should be same as the entrance in tree.
4. I tried all 4 models, but only the first model worked.

As for the stan_input, all looks fine.
![Z](https://github.com/HAMdetector/Escape.jl/assets/28436639/423830c5-d048-4bd8-a021-41d18d1d7bb5)
![X](https://github.com/HAMdetector/Escape.jl/assets/28436639/59cb54f5-0d3c-46b9-90cc-d0eb692f4133)
![phy](https://github.com/HAMdetector/Escape.jl/assets/28436639/6b12939d-3a0d-4f37-a238-3d1599ab2851)

[LHBs_test.zip](https://github.com/HAMdetector/Escape.jl/files/12842214/LHBs_test.zip)

**Comment by daniel-habermann** [comment]
Hi, I just had time to look into this.
As you didn't provide a phylogenetic tree or HLA types I had to use simulated data, but using this setup the model ran without issue.

This means that the culprit definitely lies somewhere in your input. As the first model that starts failing is model 2 (which adds phylogeny information), I strongly suspect that the phylogenetic tree is the issue here.

I've attached a phylogenetic tree that I inferred using the standard settings in HAMdetector

```julia
hla_types = rand(HLAType, 544) # random HLA types so we can run the model, we have 544 sequences in total
data =  HLAData("test", "/path/to/the/sequence/data.fasta", hla_types)
tree = Escape.phylogenetic_tree(data)

write("/path/were/you/want/the/tree.tree", Escape.newick_string(tree))
```

The branch lengths are strongly skewed with sequences 3, 84, and 152 being far away from all other sequences. Sequences 84 and 152 are also empty (containing almost only '-' and 'X' characters), so I would suggest removing them as they contain no information.

Going forward I would try the following steps:

1. Run model 4 with my phylogenetic tree provided below. If it runs we have learned that the problem is the phylogeny.

2. You mentioned that the sequences are segments of a larger protein. If you're not already doing so, I would suggest using a phylogenetic tree inferred from the larger protein, as it would capture the phylogenetic relationship between sequences much better.

3. regarding your previous point 3: It would be easiest to infer a new tree for each halving.

4. If you are still stuck, please provide a completely reproducible example (HLA types and phylogenetic tree and sequences). You can estimate phylogenetic trees with raxml-ng using the `Escape.phylogenetic_tree(hla_data)` function (might take a while, as with all phylogenetic inference methods).

**Comment by haohaohtc2010** [comment]
Hi Daniel,
I generated a phylogenetic tree following your code, and applied it to the HLAData() but still not work I attach the data (for test but error) I working with, please take a look at it.
Thanks
[data.zip](https://github.com/HAMdetector/Escape.jl/files/12923213/data.zip)

**Comment by daniel-habermann** [comment]
Hi, please see the attached files, containing a subset of the first 125 sequences.
The model works for these. I also tested a subset of sequences starting from 251 to the end, so the problem must lie somewhere between sequences 126 and 250.

I don't have time to identify the issue completely right now, but if you start adding sequences you can probably pinpoint it to a single sequence that's causing the issue.

I also noticed that the phylogenetic tree you uploaded is from the documentation. Please keep in mind that the phylogenetic tree and sequence data need to match, so you cannot take that phylogenetic tree, you have to infer one yourself using raxml-ng or other software.

You can also do it in HAMdetector directly using the code provided below

```julia
hla_types = rand(HLAType, 544) # random HLA types so we can create an HLAData object
data =  HLAData("test", "/path/to/the/sequence/data.fasta", hla_types)
tree = Escape.phylogenetic_tree(data)

write(tree, "/some/file/path.tree")
```

[testdata.zip](https://github.com/HAMdetector/Escape.jl/files/13061090/testdata.zip)

**Comment by haohaohtc2010** [comment]
Hi Daniel, sorry I thought I have replied you but seems I forgot. I located the issued entrance, where none of six HLA information are presented. Thank you for your help!

**Comment by daniel-habermann** [comment]
Awesome! I'm happy it has worked out and thank you for getting back. Please feel free to open another issue if any come up.
